//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmanage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec___Class
    {
        public int Class_Id { get; set; }
        public string Class___sec { get; set; }
        public int Class_stregnth { get; set; }
        public string Class_Teacher { get; set; }
    }
}
